node('amazon-ecs-docker-default'){
    def cluster = 'aws'
    def zone = 'eu-west-1'
    def project = 'petclinic'
    //def docker-repo = ${env.DOCKER_REPO - 'docker.photobox.com'}

    stage 'Checkout'
    git "git@github.com:Gwenall-Photobox/petclinic.git" 

    stage 'Build application Docker image'
    sh 'echo kuberctl parameters '
    withKubernetes( serverUrl: 'https://52.50.196.172', credentialsId: 'admin' ) {
    sh 'kubectl run petclinic --image=gcr.io/nicolas-deloof/petclinic --port=8080'
    sh 'kubectl delete -f  deploy/kubernetes'
    sh 'kubectl create  -f deploy/kubernetes '
    }
}
