node('amazon-ecs-docker-default'){
    def environment = 'development'
    def init
    fileLoader.withGit('git@github.com:photobox/photobox-jenkins-pipelines.git', 'master', null, '') {
        init = fileLoader.load('init.groovy');
    }
    init.init()
}
